### PR TITLE
Security proposal

### PR DESCRIPTION
**Pull request by jreidinger**
fix of https://github.com/yast/yast-installation/pull/906#issuecomment-786033802

screenshot of summary with selinux:
new_summary_selinux

### CODE REVIEW

**Review by dgdavid — APPROVED** [review]
Looks good, thank you. Just a question, are you going to fix the _priviledges_ typo in this PR?

**Comment by jreidinger** [comment]
agh, forgot to do that priviledges, will do and also plan to do manual testing with that TW skelcd

**Comment by dgdavid** [comment]
> agh, forgot to do that priviledges, 

I actually meant to the translation using _Priviledges_

https://github.com/yast/yast-installation/blob/01af9aa0d9d1cd8f34d67e042ee1f7f8649f744f/src/lib/installation/clients/security_proposal.rb#L234-L239

since I was not sure about changing the public API. Anyway, I did a quick grep and looks like it is only sure here, so your changes looks safe.

> will do and also plan to do manual testing with that TW skelcd

Great"

**Review by dgdavid — APPROVED** [review]
LGTM, thanks a lot!

**Comment by dgdavid** [comment]
Summary screen in SLES-15-SP3

Screenshot_sle15sp3-2_2021-02-26_07:31:18

**Pull request merged**
