### PR TITLE
Extra spacing in the openSUSE role selection dialog

### PR DESCRIPTION
**Pull request by ancorgs**
Now it looks like this

http://paste.opensuse.org/images/89499036.png

### CODE REVIEW

**Comment by jreidinger** [comment]
link to place where we do similar stuff for IntField https://github.com/yast/yast-yast2/blob/c2197d50e1c6b6a5b70805059139bb259ce80c7c/library/cwm/src/lib/cwm/widget.rb#L569

**Comment by okurz** [comment]
+1

**Comment by ancorgs** [comment]
@jreidinger Updated. See https://github.com/yast/yast-yast2/pull/557 (needed by this)

**Comment by jreidinger** [comment]
@ancorgs thanks for adding it, lgtm for this one is stil valid ;)

**Pull request merged**
