### PR TITLE
Added encryption_method and encryption_pbkdf in the product description file.

### PR DESCRIPTION
**Pull request by schubi2**

### CODE REVIEW

**Review by ancorgs — CHANGES_REQUESTED** [review]
If we take https://github.com/yast/yast-storage-ng/pull/1383 as reference (I think that's what we really plan to merge into master), the descriptions here are not accurate.

**Comment by schubi2** [comment]
I have changed it....

**Comment by schubi2** [comment]
> If we take [yast/yast-storage-ng#1383](https://github.com/yast/yast-storage-ng/pull/1383) as reference (I think that's what we really plan to merge into master), the descriptions here are not accurate.

I have changed it. Thanks !

**Review by ancorgs — APPROVED** [review]
LGTM

**Pull request merged**
