### PR TITLE
Improved network interfaces listing (SLE-12-GA)

### PR DESCRIPTION
**Pull request by mchf**
https://github.com/yast/yast-installation/pull/361

### CODE REVIEW

**Comment by kobliha** [comment]
If it is the same as in master, then it's definitely fine. I've checked that you use correct versioning.

so LGTM

**Comment by mchf** [comment]
well no ... this is "bottom" MU .. others should get into corresponding branches as merges of this one (SLE-12-GA merges into SLE-12-SP1 and it merges into master)

**Comment by mchf** [comment]
I've created https://github.com/yast/yast-installation/pull/361 by accident for SP1 ... it will be replaced when this PR is merged.

**Comment by kobliha** [comment]
Yes, OK, but the code is the same everywhere. The only difference will be in changes file (and version)

So LGTM still applies

**Comment by mchf** [comment]
I just wanted to make it clear for record. Thanks for review.

**Pull request merged**
