### PR TITLE
Always enable startup scripts for Second Stage and Firstboot

### PR DESCRIPTION
**Pull request by kobliha**
- The approach with %service_add_post works only for new installations but doesn't work for upgrades
- bsc#924278

### CODE REVIEW

**Comment by jreidinger** [comment]
Can we somehow detect that user want to have it disabled? Otherwise it will be quite annoying if customer try to reduce reboot time by disabled not used services and we will enable it again.

**Comment by kobliha** [comment]
1. I don't know how
2. The script checks for existence of a file and exits if file doesn't exist - cheap
3. We already ENABLE the script, always, even after online update, this only handles upgrade from SLE 11 where scripts had different name (and were not handled by systemd)

**Comment by jreidinger** [comment]
ok, so LGTM maybe add it as comment why it is fine to have it always enabled.

**Comment by kobliha** [comment]
OK, comment could help

**Pull request merged**
