### PR TITLE
Move second_stage_required?

### PR DESCRIPTION
**Pull request by imobach**
Move second_stage_required? method so it can be used by other YaST modules.

### CODE REVIEW

**Comment by imobach** [comment]
@aschnell To be used from Ruby, it's not required. But maybe it makes sense to add it so maybe we can use it from Perl. Let's ask @mvidner.

**Comment by mvidner** [comment]
So far we haven't needed it from Perl. If we did, we would have to alias the method because I doubt Perl can handle the trailing question mark.

**Comment by imobach** [comment]
@mvidner @aschnell Thanks. I've published the method and also aliased it.

**Comment by mvidner** [comment]
LGTM

**Comment by imobach** [comment]
Thanks to both of you.

**Pull request merged**
