### PR TITLE
Unifying network button position in activation of disks client. (FATE#319716)

### PR DESCRIPTION
**Pull request by teclator**
I had unified the distribution of `[Network Configuration]` button.

**Previous**
diskactivation

**Now**
diskactivationnet

### CODE REVIEW

**Comment by kobliha** [comment]
It would be nice to use a shared functionality from, e.g. yast2.rpm or something like that ~ because that would make it better for changes in the future, but it does not make the situation worse now. And it has a test case! Thanks!

LGTM (not tested, hope it works :) )

**Comment by imobach** [comment]
Better now. LGTM.

**Comment by dzedro** [comment]
fine for openQA if keyboard shortcuts don't disappear or change :+1: 
no keyboard shortcuts is bad, test will fail :sob: 
different keyboard shortcuts can be changed in openQA too :construction_worker:

**Comment by imobach** [comment]
@dzedro Thanks for pointing it out. @teclator According to screenshots, it looks like the shortcut for network configuration has changed. But, to be honest, I'm not sure if this scenario is tested in openQA.

PS: anyway, it's good to have it present for the future.

**Comment by dzedro** [comment]
e.g. iSCSI test is using [disk activation](https://openqa.suse.de/tests/333427/modules/iscsi_configuration/steps/1)
openQA is matching specific screen areas and this change will not affect existing needles

**Comment by teclator** [comment]
@dzedro yeah, i'm fixing it, i just unified labels text as it was in Registration but i removed the previous shortcut with a dynamic one, so i will unify buttons and fix it. Thnx for your help and time.

**Comment by imobach** [comment]
LGTM

**Pull request merged**
