### PR TITLE
Casp services

### PR DESCRIPTION
**Pull request by jreidinger**
tested manually

https://fate.suse.com/321738

### CODE REVIEW

**Comment by imobachgs** [comment]
The code looks ok but I'm not sure if I like this solution:

1) I don't like having a hardcoded list of services. I would move the list to the control file.
2) As it's only in the one-dialog, AutoYaST won't benefit of it. But maybe AutoYaST is out of the scope here.

Well, that's just an opinion but I would like to discuss it :)

**Comment by jreidinger** [comment]
@imobachgs well, if it will be in control file it means we need to adapt control file schema and also control file beside others, but on other hand we need to add such support as generic support and not as caasp only. And if we do it, then there is high risk, that they start to use it instead of systemd-presets ( which in PBI is mentioned that for this purpose cannot be used ). So I would like to keep it as exception for caasp only as it have tricky services.
Regarding autoyast, it is mentioned, that autoyast is not affected, as it should have these services in autoyast template.

**Comment by mvidner** [comment]
https://fate.suse.com/321738 explicitly calls for the list of the services to come from the control file. Neither the code nor the commit message explain why we hardcode it instead.

**Comment by jreidinger** [comment]
@mvidner I added comment and to be honest I reuse this FATE from roles services PBI. This request come via instant messaging from kukuk and to be honest original proposal was to run it in shell script :) This way it can be at least debugged.

**Comment by imobachgs** [comment]
The dialog is CaaSP specific and won't be reusable at all. But now it's documented so I'm fine. The code looks good and I'm only missing a unit test :)

**Pull request merged**
